"""
Tier-2 -- emulated convergence of the deploy/ Terraform against moto.

Proves the whole graph converges: dependency ordering resolves, every
jsonencode()'d policy is API-acceptable JSON, ARNs interpolate, no collisions.
"""
import os
import shutil
import subprocess
import pytest
import iac_deploy_mirror as M

pytestmark = pytest.mark.tier2

_ENDPOINT_SERVICES = [
    "kms", "s3", "sqs", "dynamodb", "iam", "lambda",
    "eventbridge", "cloudformation", "sts", "ec2", "logs", "guardduty",
    "secretsmanager", "cloudwatch",
]

def _override_tf(endpoint):
    blocks = "\n".join(f'    {svc} = "{endpoint}"' for svc in _ENDPOINT_SERVICES)
    return f'''# generated by tier2 -- do not commit
provider "aws" {{
  region                      = "us-east-1"
  access_key                  = "test"
  secret_key                  = "test"
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  endpoints {{
{blocks}
  }}
}}
'''

@pytest.fixture(scope="session")
def _plugin_cache(tmp_path_factory):
    # Share provider downloads across all three connector params + init/apply,
    # turning ~3x full provider pulls into one (the first run took ~16m largely
    # on repeated provider downloads).
    d = tmp_path_factory.mktemp("tf_plugin_cache")
    return str(d)

def _patch_backend_to_local(workdir):
    """Replace backend "s3" {} with backend "local" {} so terraform apply
    works without real S3 credentials during container-based testing.
    The partial config approach (backend "s3" {}) requires -backend-config
    flags at deploy time; for tests we swap in local state."""
    for tf_file in workdir.glob("*.tf"):
        content = tf_file.read_text()
        patched = content.replace('backend "s3" {}', 'backend "local" {}')
        if patched != content:
            tf_file.write_text(patched)

@pytest.fixture
def tf_workdir(tf_dir, tmp_path, moto_endpoint, _plugin_cache):
    if not shutil.which("terraform"):
        pytest.skip("terraform not installed (present in the tier2 container)")
    dst = tmp_path / "tf"
    shutil.copytree(tf_dir, dst)
    _patch_backend_to_local(dst)
    (dst / "zz_moto_override.tf").write_text(_override_tf(moto_endpoint))
    stub = dst / "orchestrator_payload.zip"
    if not stub.exists():
        import zipfile
        with zipfile.ZipFile(stub, "w") as z:
            z.writestr("bootstrap", "#!/bin/sh\n")
    return dst

def _tf(workdir, *args, cache=None):
    env = {**os.environ, "AWS_ACCESS_KEY_ID": "test", "AWS_SECRET_ACCESS_KEY": "test",
           "AWS_DEFAULT_REGION": "us-east-1"}
    if cache:
        env["TF_PLUGIN_CACHE_DIR"] = cache
    return subprocess.run(["terraform", *args], cwd=workdir, env=env,
                          capture_output=True, text=True)

class TestTerraformConverges:
    def test_init_and_validate(self, tf_workdir, connector_name, _plugin_cache):
        # -backend=false: skips remote backend init; backend config is provided at
        # deploy time via -backend-config flags, not baked into the source.
        r = _tf(tf_workdir, "init", "-no-color", "-input=false", "-backend=false", cache=_plugin_cache)
        assert r.returncode == 0, f"{connector_name}: init failed\n{r.stderr[-2000:]}"
        r = _tf(tf_workdir, "validate", "-no-color")
        assert r.returncode == 0, f"{connector_name}: validate failed\n{r.stderr[-2000:]}"

    def test_fmt_clean(self, tf_dir, connector_name):
        if not shutil.which("terraform"):
            pytest.skip("terraform not installed")
        r = subprocess.run(["terraform", "fmt", "-check", "-recursive", tf_dir],
                            capture_output=True, text=True)
        assert r.returncode == 0, f"{connector_name}: `terraform fmt` would reformat:\n{r.stdout}"

    def test_apply_graph_converges_against_emulator(self, tf_workdir, tf_src, connector_name, _plugin_cache):
        profile = M.CONNECTOR_PROFILE.get(connector_name, {})
        unsupported = [s for s in profile.get("emulator_unsupported", []) if s in tf_src]
        if unsupported:
            pytest.skip(
                f"{connector_name}: stack uses {unsupported} which moto cannot faithfully "
                f"emulate (e.g. data.aws_guardduty_detector) -- convergence deferred to "
                f"the gated real-AWS run"
            )
        # No -backend=false here: the workdir has backend "local" {} (patched by tf_workdir
        # fixture), so init must configure the local backend before apply can use it.
        r = _tf(tf_workdir, "init", "-no-color", "-input=false", cache=_plugin_cache)
        assert r.returncode == 0, f"{connector_name}: init failed\n{r.stderr[-1500:]}"
        r = _tf(tf_workdir, "apply", "-no-color", "-auto-approve", "-input=false", cache=_plugin_cache)
        assert r.returncode == 0, (
            f"{connector_name}: apply did not converge against moto:\n{r.stderr[-3000:]}"
        )
        _tf(tf_workdir, "destroy", "-no-color", "-auto-approve", "-input=false", cache=_plugin_cache)