#!/usr/bin/env python3
"""
Control-evidence generator — embeds the *actual code* that satisfies each control.

For every control in `evidence_map.yaml`, this extracts the cited source snippet(s)
(anchored on a unique substring, with a `file:Lstart-Lend` citation) and writes:

  * artifacts/<CONTROL-ID>.md   — the per-control evidence fragment, and
  * control_evidence.md         — the consolidated "Control Evidence Dossier" (→ PDF).

Because each snippet is anchored on a substring rather than a line number, the
evidence tracks the code: rename/move the anchored symbol and the drift test
(test_governance_manifest.py::TestControlEvidence) fails until this is regenerated.

Usage:
  gen_evidence.py            # (re)write artifacts/*.md + control_evidence.md
  gen_evidence.py --check    # exit 1 if any artifact is stale or an anchor is missing
"""
import sys
from collections import OrderedDict
from pathlib import Path

import yaml

HERE = Path(__file__).parent
PE = HERE.parent.parent                      # project_empros/
EVIDENCE_MAP = HERE / "evidence_map.yaml"
MANIFEST = HERE / "controls_manifest.yaml"
ARTIFACTS = HERE / "artifacts"
DOSSIER = HERE / "control_evidence.md"
SSP = HERE / "system_security_plan.md"
_SSP_BEGIN = "<!-- BEGIN EVIDENCE INDEX (generated by gen_evidence.py — do not edit by hand) -->"
_SSP_END = "<!-- END EVIDENCE INDEX -->"

_LANG = {".py": "python", ".rs": "rust", ".sh": "bash",
         ".yml": "yaml", ".yaml": "yaml", ".md": "text", ".tf": "terraform"}


def load_evidence_map():
    return (yaml.safe_load(EVIDENCE_MAP.read_text()) or {}).get("evidence", {}) or {}


def _titles():
    m = yaml.safe_load(MANIFEST.read_text())
    return {c["id"]: c for c in m.get("controls", [])}


class AnchorError(ValueError):
    pass


def extract_snippet(entry):
    """Return (lang, citation, code) for one evidence entry, or raise AnchorError."""
    path = PE / entry["file"]
    if not path.exists():
        raise AnchorError(f"evidence file missing: {entry['file']}")
    lines = path.read_text(errors="replace").splitlines()
    anchor = entry["anchor"]
    idx = next((i for i, ln in enumerate(lines) if anchor in ln), None)
    if idx is None:
        raise AnchorError(f"anchor not found in {entry['file']!r}: {anchor!r}")
    before, after = int(entry.get("before", 0)), int(entry.get("after", 0))
    start, end = max(0, idx - before), min(len(lines), idx + after + 1)
    snippet = "\n".join(lines[start:end])
    lang = _LANG.get(path.suffix, "text")
    citation = f"{entry['file']}:L{start + 1}-L{end}"
    return lang, citation, snippet


def render_control(cid, entries, titles):
    ctl = titles.get(cid, {})
    L = [f"### {cid} — {ctl.get('title', cid)}", ""]
    impl = ctl.get("implementation")
    if impl:
        impl = [impl] if isinstance(impl, str) else impl
        L += ["*Implementation: " + ", ".join(f"`{p}`" for p in impl) + "*", ""]
    for entry in entries:
        lang, citation, snippet = extract_snippet(entry)
        L += [entry.get("caption", "").strip(), "", f"`{citation}`", "",
              "```" + lang, snippet, "```", ""]
    return L


def render_dossier(evidence, titles):
    L = ["---", 'title: "Control Evidence Dossier"',
         'subtitle: "Sentinel Nexus — the code that answers each control"',
         'author: "Information Security & AI Governance"', 'date: "June 2026"',
         'version: "1.0"', "---", "",
         "<!-- GENERATED FILE — DO NOT EDIT BY HAND. Source: evidence_map.yaml + the cited "
         "code. Regenerate: ./gen_evidence.py -->", "",
         "\\newpage", "", "## Purpose", "",
         "This dossier answers each control with the **actual source code** that satisfies "
         "it — extracted directly from the repository and cited by `file:line`. Each snippet "
         "is anchored to a symbol, not a line number, so the dossier cannot silently drift "
         "from the code (CI fails if an anchor moves). Several controls are answered by the "
         "*culmination* of snippets across multiple files.", "", "\\newpage", ""]
    for cid in sorted(evidence):
        L += render_control(cid, evidence[cid], titles)
        L += ["\\newpage", ""]
    return "\n".join(L).rstrip() + "\n"


def render_fragment(cid, entries, titles):
    # per-control artifact file (no frontmatter; '#'-level heading)
    body = render_control(cid, entries, titles)
    body[0] = body[0].replace("### ", "# ", 1)
    return "\n".join(body).rstrip() + "\n"


def render_ssp_index(evidence, titles):
    """The Annex-B body inserted between the SSP evidence-index markers.

    Rendered as a wrapping definition list (not a table) so long `file:line`
    citations never overflow the portrait page.
    """
    L = [""]
    for cid in sorted(evidence):
        # collapse to basename + line-ranges so no path token overruns the portrait margin;
        # the full path lives in artifacts/<cid>.md and the dossier.
        per_file = OrderedDict()
        for e in evidence[cid]:
            citation = extract_snippet(e)[1]                # "path:Lx-Ly"
            path, lines = citation.rsplit(":", 1)
            per_file.setdefault(path.split("/")[-1], []).append(lines)
        cites = "; ".join(f"{b} {','.join(ls)}" for b, ls in per_file.items())
        title = titles.get(cid, {}).get("title", cid)
        # plain bulleted list (no code spans / description labels) so the line wraps and
        # hyphenated control ids / paths break on the portrait page.
        L.append(f"- **{cid}** — {title}. *Evidence:* artifacts/{cid}.md — {cites}")
    L.append("")
    return "\n".join(L)


def _ssp_with_index(evidence, titles):
    """Return the SSP text with the Annex-B index region refreshed (or None if no markers)."""
    if not SSP.exists():
        return None
    text = SSP.read_text()
    if _SSP_BEGIN not in text or _SSP_END not in text:
        return None
    head, rest = text.split(_SSP_BEGIN, 1)
    _old, tail = rest.split(_SSP_END, 1)
    return f"{head}{_SSP_BEGIN}\n{render_ssp_index(evidence, titles)}\n{_SSP_END}{tail}"


def build_outputs():
    evidence, titles = load_evidence_map(), _titles()
    outputs = {DOSSIER: render_dossier(evidence, titles)}
    for cid, entries in evidence.items():
        outputs[ARTIFACTS / f"{cid}.md"] = render_fragment(cid, entries, titles)
    ssp = _ssp_with_index(evidence, titles)
    if ssp is not None:
        outputs[SSP] = ssp
    return outputs


def main(argv):
    ARTIFACTS.mkdir(exist_ok=True)
    try:
        outputs = build_outputs()
    except AnchorError as e:
        print(f"EVIDENCE ANCHOR ERROR: {e}", file=sys.stderr)
        return 1
    if "--check" in argv:
        stale = [p.name for p, exp in outputs.items()
                 if (p.read_text() if p.exists() else "") != exp]
        if stale:
            print(f"DRIFT: {stale} out of sync with the code/evidence_map. "
                  f"Run `gen_evidence.py` and commit.", file=sys.stderr)
            return 1
        print("control-evidence artifacts are in sync.")
        return 0
    for p, exp in outputs.items():
        p.write_text(exp)
    print(f"wrote {len(outputs)} evidence artifacts (+ dossier) under {ARTIFACTS.name}/")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
