#!/usr/bin/env bash
# ==============================================================================
# Sentinel Nexus -- Ephemeral Secrets Bootstrap
# Generates ALL required secrets for the operations stack.
# ==============================================================================

source "$(dirname "$0")/lib.sh"

log_step "Ephemeral Secrets Generator"

if [[ -f "$NEXUS_ENV_FILE" ]]; then
    log_warn "${NEXUS_ENV_FILE} already exists."
    if [[ "${1:-}" != "--force" ]]; then
        log_info "Pass --force to regenerate. Aborting to protect existing OIDC state."
        exit 0
    fi
    log_warn "Force flag set -- regenerating all secrets."
    cp "$NEXUS_ENV_FILE" "${NEXUS_ENV_FILE}.bak.$(date +%s)"
fi

require_cmd openssl
require_cmd ssh-keygen

# -- Generate cryptographically secure secrets --
N8N_ENCRYPTION_KEY=$(openssl rand -hex 32)
WEBUI_SECRET_KEY=$(openssl rand -base64 32)
JWT_SECRET=$(openssl rand -hex 32)
AUTHENTIK_SECRET_KEY_VALUE=$(openssl rand -hex 32)
PG_PASS=$(openssl rand -hex 24)
OAUTH_CLIENT_ID="nexus-$(openssl rand -hex 8)"
OAUTH_CLIENT_SECRET=$(openssl rand -hex 32)
EDR_API_KEY=$(openssl rand -hex 24)
FW_API_KEY=$(openssl rand -hex 24)
S3_ACCESS_KEY=$(openssl rand -hex 12)
S3_SECRET_KEY=$(openssl rand -hex 24)
# Shared secret for HMAC-SHA256 integrity verification of cloud containment
# callbacks (Lambda → n8n, GCP Function → n8n). Must match the value supplied
# to Terraform via -var="nexus_shared_secret=..." in 02-provision-infra.sh.
NEXUS_SHARED_SECRET=$(openssl rand -hex 32)
# Alias used by n8n workflows and containment.toml headers: ${NEXUS_HMAC_SECRET}
NEXUS_HMAC_SECRET="${NEXUS_SHARED_SECRET}"
# NATS HTTP management API -- used by Cloud_Containment workflow to signal SOAR
NATS_HTTP_URL="${NATS_HTTP_URL:-http://nats-server:8222}"

# -- Generate SSH key for nexus-responder playbook delivery --
SSH_KEY_DIR="${OPS_ROOT}/ssh"
SSH_KEY_FILE="${SSH_KEY_DIR}/id_ecdsa"
mkdir -p "${SSH_KEY_DIR}"
if [[ ! -f "${SSH_KEY_FILE}" || "${1:-}" == "--force" ]]; then
    ssh-keygen -t ecdsa -b 521 -f "${SSH_KEY_FILE}" -N "" \
        -C "nexus-responder@sentinel-nexus-$(date +%Y%m%d)" -q
    chmod 600 "${SSH_KEY_FILE}"
    chmod 644 "${SSH_KEY_FILE}.pub"
    log_ok "SSH key pair generated at ${SSH_KEY_FILE}"
    log_info "Public key (deploy to managed endpoints as nexus-responder):"
    log_info "  $(cat "${SSH_KEY_FILE}.pub")"
else
    log_info "SSH key already exists at ${SSH_KEY_FILE} (pass --force to regenerate)."
fi

log_info "Writing secrets to ${NEXUS_ENV_FILE}..."

cat > "$NEXUS_ENV_FILE" << EOF
# ==============================================================================
# Sentinel Nexus -- Operations Environment
# Auto-generated by scripts/env-gen.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ==============================================================================

# -- 1. Interface Secrets --
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
JWT_SECRET=${JWT_SECRET}

# -- 2. Database --
PG_PASS=${PG_PASS}

# -- 3. Authentik SSO / OIDC --
OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
OPENID_PROVIDER_URL=https://${NEXUS_DOMAIN_SSO}/application/o/${NEXUS_SSO_OAUTH_APP_SLUG}/
AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY_VALUE}

# -- 4. Containment Provider Keys --
EDR_API_KEY=${EDR_API_KEY}
FW_API_KEY=${FW_API_KEY}

# -- 5. S3 / Data Lake --
NEXUS_S3_ACCESS_KEY=${S3_ACCESS_KEY}
NEXUS_S3_SECRET_KEY=${S3_SECRET_KEY}

# -- 6. Domain Routing (mirrored from nexus.conf) --
NEXUS_DOMAIN_SSO=${NEXUS_DOMAIN_SSO}
NEXUS_DOMAIN_N8N=${NEXUS_DOMAIN_N8N}
NEXUS_DOMAIN_WEBUI=${NEXUS_DOMAIN_WEBUI}

# -- 7. Inference Routing --
OLLAMA_BASE_URL=${NEXUS_OLLAMA_URL}
OPENAI_API_BASE_URLS=${NEXUS_VLLM_URL}

# -- 8. n8n Webhook Routing --
VUE_APP_URL=https://${NEXUS_DOMAIN_N8N}
WEBHOOK_URL=https://${NEXUS_DOMAIN_N8N}

# -- 9. Cloud Containment Secrets --
# NEXUS_SHARED_SECRET and NEXUS_HMAC_SECRET are the same value.
# Both names are used across subsystems for historical reasons.
NEXUS_SHARED_SECRET=${NEXUS_SHARED_SECRET}
NEXUS_HMAC_SECRET=${NEXUS_HMAC_SECRET}
# NATS HTTP API endpoint for Cloud_Containment workflow callback publishing.
NATS_HTTP_URL=${NATS_HTTP_URL}
# Cloud endpoint URLs are injected by 02-provision-infra.sh AFTER Terraform apply.
# Placeholders here; overwritten on first provisioning run:
AWS_ISOLATE_LAMBDA_URL=${AWS_ISOLATE_LAMBDA_URL:-}
AWS_BLOCK_IP_LAMBDA_URL=${AWS_BLOCK_IP_LAMBDA_URL:-}
AZURE_NSG_WEBHOOK_URL=${AZURE_NSG_WEBHOOK_URL:-}
GCP_ISOLATE_FUNCTION_URL=${GCP_ISOLATE_FUNCTION_URL:-}
EOF

chmod 600 "$NEXUS_ENV_FILE"

log_ok "All secrets generated and written."
log_info "OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}"
log_info "Secrets file permissions set to 600 (owner-only read/write)."