#
# Sentinel Nexus Telemetry -- Splunk App
# Deploy to $SPLUNK_HOME/etc/apps/nexus_telemetry/
#

[install]
is_configured = false
build = 1

[ui]
is_visible = true
label = Sentinel Nexus Telemetry

[launcher]
author = Sentinel Nexus
description = Indexes, sourcetypes, and CIM-compliant field mappings for all Sentinel Nexus sensor telemetry (endpoint, cloud, network).
version = 1.0.0

[package]
id = nexus_telemetry
check_for_updates = false
