#
# Sentinel Nexus -- Search Macros
# Shortcuts for SOC analysts working with sensor telemetry.
#

[nexus_all]
definition = index=nexus_endpoint OR index=nexus_cloud OR index=nexus_network OR index=nexus_alerts

[nexus_endpoint]
definition = index=nexus_endpoint

[nexus_cloud]
definition = index=nexus_cloud

[nexus_network]
definition = index=nexus_network

[nexus_high_risk]
definition = (index=nexus_endpoint OR index=nexus_cloud) score>=70

[nexus_by_dest(1)]
args = ip
definition = (`nexus_all`) dest="$ip$"

[nexus_by_process(1)]
args = name
definition = (`nexus_endpoint`) app="$name$"

[nexus_beacons]
definition = (`nexus_endpoint`) sourcetype="nexus:c2:linux" cv<0.15 interval>0

[nexus_selfsigned_certs]
definition = (`nexus_network`) sourcetype="nexus:nettap:session" cert_self_signed=1

[nexus_failed_auth]
definition = (`nexus_cloud`) sourcetype="nexus:entraid:signin" score>=50

[nexus_lateral_movement]
definition = (`nexus_endpoint`) (mitre_tactic="Lateral Movement" OR tactic="Lateral Movement")

[nexus_ingest_health]
definition = index=_internal sourcetype=splunk_httpinput_metrics group=per_token token_name="Nexus_Middleware"
