#!/bin/bash
# ==============================================================================
# Sentinel Nexus -- Secure Environment Configuration Builder
# ==============================================================================
set -e

C_CYAN="\033[1;36m"
C_GREEN="\033[1;32m"
C_YELLOW="\033[1;33m"
C_RESET="\033[0m"

ENV_FILE="nexus.env"

echo -e "${C_CYAN}[*] Initializing Sentinel Nexus Environment Builder${C_RESET}"
echo -e "${C_YELLOW}[!] This data will be stored locally in ${ENV_FILE}${C_RESET}\n"

# Touch the file and lock permissions before writing secrets
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

cat <<EOF > "$ENV_FILE"
# ==============================================================================
# Sentinel Nexus Runtime Environment Variables
# Auto-generated by setup_env.sh
# ==============================================================================

EOF

# ── 1. NATS Security ──────────────────────────────────────────────────────────
echo -e "${C_CYAN}--- NATS Authentication ---${C_RESET}"
read -p "Enter NATS JetStream NKey Seed (Starts with 'SU'): " NATS_SEED
echo "NATS_NKEY_SEED=${NATS_SEED}" >> "$ENV_FILE"

# ── 2. AWS / S3 / MinIO Storage ───────────────────────────────────────────
echo -e "\n${C_CYAN}--- S3 / MinIO Storage ---${C_RESET}"
read -p "Enter S3 Bucket Name: " S3_BUCKET
read -p "Enter S3 Endpoint (Leave blank for AWS): " S3_ENDPOINT
read -p "Enter Access Key ID: " AWS_ACCESS_KEY
read -s -p "Enter Secret Access Key: " AWS_SECRET_KEY
echo ""

echo "S3_BUCKET_NAME=${S3_BUCKET}" >> "$ENV_FILE"
echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}" >> "$ENV_FILE"
echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}" >> "$ENV_FILE"

if [ -n "$S3_ENDPOINT" ]; then
    echo "S3_ENDPOINT=${S3_ENDPOINT}" >> "$ENV_FILE"
fi

# ── 3. AI / LLM Providers ─────────────────────────────────────────────────────
echo -e "\n${C_CYAN}--- LLM Correlation Engine ---${C_RESET}"
read -s -p "Enter OpenAI API Key (Leave blank if unused): " OPENAI_KEY
echo ""
read -s -p "Enter Anthropic API Key (Leave blank if unused): " ANTHROPIC_KEY
echo ""

if [ -n "$OPENAI_KEY" ]; then echo "OPENAI_API_KEY=${OPENAI_KEY}" >> "$ENV_FILE"; fi
if [ -n "$ANTHROPIC_KEY" ]; then echo "ANTHROPIC_API_KEY=${ANTHROPIC_KEY}" >> "$ENV_FILE"; fi

# ── 4. Incident Webhook ───────────────────────────────────────────────────────
echo -e "\n${C_CYAN}--- Case Management / SOAR ---${C_RESET}"
read -p "Enter Incident Webhook URL (Slack, TheHive, Jira): " WEBHOOK_URL
echo "INCIDENT_WEBHOOK_URL=${WEBHOOK_URL}" >> "$ENV_FILE"

echo -e "\n${C_GREEN}[+] Environment file generated successfully: ${ENV_FILE}${C_RESET}"
echo -e "${C_YELLOW}[!] Permissions locked to 600. Do not commit this file to version control.${C_RESET}"

# ── 5. Ingress Security & Data Pipeline ──────────────────────────────────
echo -e "\n${C_CYAN}--- Ingress API Security ---${C_RESET}"
JWT_GEN=$(openssl rand -base64 32)
read -p "Enter JWT Secret (Press Enter to use generated: ${JWT_GEN}): " USER_JWT
JWT_SECRET=${USER_JWT:-$JWT_GEN}
echo "JWT_SECRET=${JWT_SECRET}" >> "$ENV_FILE"

HMAC_GEN=$(openssl rand -base64 32)
read -p "Enter Integrity HMAC Secret (Press Enter to use generated: ${HMAC_GEN}): " USER_HMAC
HMAC_SECRET=${USER_HMAC:-$HMAC_GEN}
echo "INTEGRITY_HMAC_SECRET=${HMAC_SECRET}" >> "$ENV_FILE"

read -p "Enter Integrity Ban Threshold (Default: 5): " BAN_THRESH
echo "INTEGRITY_BAN_THRESHOLD=${BAN_THRESH:-5}" >> "$ENV_FILE"

read -p "Enter Max Payload Bytes (Default: 10485760): " MAX_PAYLOAD
echo "MAX_PAYLOAD_BYTES=${MAX_PAYLOAD:-10485760}" >> "$ENV_FILE"

read -p "Enter DLQ Prefix (Default: nexus.dlq): " DLQ_PREF
echo "DLQ_PREFIX=${DLQ_PREF:-nexus.dlq}" >> "$ENV_FILE"